name: Reusable deploy workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Artifact name to be used in Deploying
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Outcome of deployment
        value: ${{ jobs.deploy.outputs.deploy-result }}
    #secrets:
      #some-secret:
        #required: false
jobs:
  deploy:
    outputs: 
      deploy-result: ${{ steps.result-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output files
        run: ls
      - name: Output information
        run: echo "Deploying and Uploading to AWS..."
      - name: Set result output
        id: result-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT